version: '3.8'

services:
  api:
    build: ./app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=mongodb://edelacruz:sip18DNK.*@10.89.4.2:27017
      - SECRET_KEY=bgvfcdxs654321
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=edelacruz
      - MONGO_INITDB_ROOT_PASSWORD=sip18DNK.*
    volumes:
      - data:/data/db


volumes:
  data:
